version: '3'

vars:
  ASYNC_PROFILER_DIR: "{{.TASK_DIR}}/.local/async-profiler"
  BENCHMARKS_OUTPUT_DIR: "{{.TASK_DIR}}/target/benchmarks"
  BENCHMARKS_JAR: "target/benchmarks.jar"

tasks:

  download-async-profiler-linux-x64:
    desc: "Install async-profiler (Linux x64)"
    platforms:
      - linux
    vars:
      ASYNC_PROFILER_VERSION: "4.1"
      ASYNC_PROFILER_URL: "https://github.com/async-profiler/async-profiler/releases/download/v{{.ASYNC_PROFILER_VERSION}}/async-profiler-{{.ASYNC_PROFILER_VERSION}}-linux-x64.tar.gz"
      ASYNC_PROFILER_ARCHIVE: "async-profiler-{{.ASYNC_PROFILER_VERSION}}-linux-x64.tar.gz"
      VERSION_FILE: "{{.ASYNC_PROFILER_DIR}}/.version"
    cmds:
      - curl -L -o {{.ASYNC_PROFILER_ARCHIVE}} {{.ASYNC_PROFILER_URL}}
      - rm -rf {{.ASYNC_PROFILER_DIR}}
      - mkdir -p {{.ASYNC_PROFILER_DIR}}
      - tar xzf {{.ASYNC_PROFILER_ARCHIVE}} --strip-components=1 -C {{.ASYNC_PROFILER_DIR}}
      - echo "{{.ASYNC_PROFILER_VERSION}}" > {{.VERSION_FILE}}
      - rm {{.ASYNC_PROFILER_ARCHIVE}}
    sources:
      - Taskfile.yml
    generates:
      - "{{.ASYNC_PROFILER_DIR}}/lib/libasyncProfiler.so"
    status:
      - test -f "{{.VERSION_FILE}}" && test "$(cat {{.VERSION_FILE}})" = "{{.ASYNC_PROFILER_VERSION}}"
  download-async-profiler-macos:
    desc: "Install async-profiler (MacOS)"
    platforms:
      - darwin
    vars:
      ASYNC_PROFILER_VERSION: "4.1"
      ASYNC_PROFILER_URL: "https://github.com/async-profiler/async-profiler/releases/download/v{{.ASYNC_PROFILER_VERSION}}/async-profiler-{{.ASYNC_PROFILER_VERSION}}-linux-x64.tar.gz"
      ASYNC_PROFILER_ARCHIVE: "async-profiler-{{.ASYNC_PROFILER_VERSION}}-macos.zip"
      VERSION_FILE: "{{.ASYNC_PROFILER_DIR}}/.version"
    cmds:
      - curl -L -o {{.ASYNC_PROFILER_ARCHIVE}} {{.ASYNC_PROFILER_URL}}
      - rm -rf {{.ASYNC_PROFILER_DIR}}
      - mkdir -p {{.ASYNC_PROFILER_DIR}}
      - tar xzf {{.ASYNC_PROFILER_ARCHIVE}} --strip-components=1 -C {{.ASYNC_PROFILER_DIR}}
      - echo "{{.ASYNC_PROFILER_VERSION}}" > {{.VERSION_FILE}}
      - rm {{.ASYNC_PROFILER_ARCHIVE}}
    sources:
      - Taskfile.yml
    generates:
      - "{{.ASYNC_PROFILER_DIR}}/lib/libasyncProfiler.so"
    status:
      - test -f "{{.VERSION_FILE}}" && test "$(cat {{.VERSION_FILE}})" = "{{.ASYNC_PROFILER_VERSION}}"
  build:
    desc: "Build all modules with Maven"
    cmds:
      - cmd: ./mvnw --batch-mode --update-snapshots clean verify
        platforms: [linux, darwin]
      - cmd: cmd /c "mvnw.cmd --batch-mode --update-snapshots clean verify"
        platforms: [windows]
    sources:
      - "pom.xml"
      - "**/src/main/java/**"
      - "**/src/test/java/**"
    generates:
      - "**/target/classes/**"
      - "**/target/test-classes/**"
      - "{{.BENCHMARKS_JAR}}"
  run-all-benchmarks:
    desc: "Run JMH benchmarks"
    deps:
      - build
    cmds:
      - java -jar {{.BENCHMARKS_JAR}} -wi 3 -i 5 -f 1
  run-benchmark:
    desc: "Run a specific benchmark (usage: task run-specific-benchmark -- BenchmarkClassName)"
    deps:
      - build
    cmds:
      - java -jar {{.BENCHMARKS_JAR}} "{{.CLI_ARGS}}" -wi 3 -i 5 -f 1
  profile-benchmark:
    desc: "Profile benchmarks using async-profiler"
    deps:
      - download-async-profiler-linux-x64
      - build
    cmds:
      - mkdir -p {{.BENCHMARKS_OUTPUT_DIR}}
      - |
        java -jar {{.BENCHMARKS_JAR}} \
        "{{.CLI_ARGS}}" \
        -wi 5 -i 5 -f 1 \
        -prof "async:libPath={{.ASYNC_PROFILER_DIR}}/lib/libasyncProfiler.so;event=wall;output=collapsed;threads=true;dir={{.BENCHMARKS_OUTPUT_DIR}}"
